### ISSUE TITLE
Points over par should give double

### ISSUE THREAD

**Issue by nicce** [nicce/tour-le-shit#11]
Points over Par (over 36) should give double.
For example:

```
stablefordPoints = 38
pointsOverPar = (38-36) * 2  =4
```

**Comment by nicce** [comment]
@MarcusEngberg as a product owner, what is your take on this suggestion from a user of tour-le-shit?

**Comment by MarcusEngberg** [comment]
After having a close view of customers in action today I feel more points are needed! This will be a nice addition for the app
