### ISSUE TITLE
Snek not moving to new owner

### ISSUE THREAD

**Issue by MarcusEngberg** [nicce/tour-le-shit#9]

**Comment by nicce** [comment]
🐍

**Comment by MarcusEngberg** [comment]
Player Hendess earned the honour with snek in last round - when updating his score the symbol of snek did not move to his name.

**Comment by nicce** [comment]
Fixed, shouldn't happen again. I can only offer my most sincere apologies.

**Comment by MarcusEngberg** [comment]
we will see after next user test....trust has been severely damaged
